In [8]:
import pandas as pd

df = pd.read_csv('mlb-pitch-data-20152018/pitches.csv')

0    FF
1    FF
2    FF
3    FF
4    CU
Name: pitch_type, dtype: object

In [26]:
df.drop_duplicates(inplace=True)
df = df[df.pitch_type != 'UN']

In [28]:
df[['ab_id','break_angle', 'break_length', 'end_speed', 'pitch_type']].head()

          ab_id  break_angle  break_length  end_speed pitch_type
0  2.015000e+09        -25.0           3.2       84.1         FF
1  2.015000e+09        -40.7           3.4       84.1         FF
2  2.015000e+09        -43.7           3.7       85.2         FF
3  2.015000e+09         -1.3           5.0       84.0         FF
4  2.015000e+09         18.4          12.0       69.6         CU

In [32]:
four_seam_fast_ball = df[df.pitch_type == 'FF']
change_up = df[df.pitch_type == 'CH']
curve_ball = df[df.pitch_type == 'CB']
eephus = df[df.pitch_type == 'EP']
cutter = df[df.pitch_type == 'FC']
pitchout = df[df.pitch_type == 'FO' or df.pitch_type == 'PO']
splitter = df[df.pitch_type == 'FS']
two_seam_fastball = df[df.pitch_type == 'FT']
intentional_ball = df[df.pitch_type == 'IN']
knuckle_curve = df[df.pitch_type == 'KC']
knuckle_ball = df[df.pitch_type == 'KN']
screwball = df[df.pitch_type == 'SC']
sinker = df[df.pitch_type == 'SI']
slider = df[df.pitch_type == 'SL']

fast_ball[['ab_id','break_angle', 'break_length', 'end_speed', 'pitch_type']].head()

          ab_id  break_angle  break_length  end_speed pitch_type
0  2.015000e+09        -25.0           3.2       84.1         FF
1  2.015000e+09        -40.7           3.4       84.1         FF
2  2.015000e+09        -43.7           3.7       85.2         FF
3  2.015000e+09         -1.3           5.0       84.0         FF
5  2.015000e+09        -45.7           3.7       84.8         FF

            ab_id  break_angle  break_length  end_speed pitch_type
36   2.015000e+09        -29.8           8.2       76.2         CH
109  2.015000e+09         32.4           6.8       77.3         CH
113  2.015000e+09        -25.5           8.5       73.9         CH
124  2.015000e+09        -26.5           6.9       78.8         CH
148  2.015000e+09        -28.6           6.6       79.4         CH

In [ ]:
from mpl.toolkits.mplot3d import Axes3d
import matplotlib.pyplot as plt